### ISSUE TITLE
NullPointerException occurring on nested fields with decimal-Type

### ISSUE THREAD

**Issue by noahboerger** [Norsk-Tipping/kafka-connect-jdbc-flatten#1]
### Describe the bug

When using nested avro-types, which are flattened by the connector, it is no more possible for the connector to create the base table because the sql-type for the decimal types can not be  determined 

e.g. the following avro-scheme is affected because of the field "sample_decimal":

```json
{
  "namespace": "de.bundesbank.digistik.avro",
  "name": "TestStammdatum",
  "type": "record",
  "fields": [
    {
      "name": "sample_field",
      "type": "string"
    },
    {
      "name": "test_stammdaten",
      "default": null,
      "type": [
        "null",
        {
          "type": "record",
          "name": "TestStammdaten",
          "fields": [
            {
              "name": "sample_decimal",
              "default": null,
              "type": [
                "null",
                {
                  "type": "bytes",
                  "logicalType": "decimal",
                  "precision": 33,
                  "scale": 12
                }
              ]
            },
            {
              "name": "sample_array",
              "default": [],
              "type": {
                "type": "array",
                "items": "string"
              }
            }
          ]
        }
      ]
    }
  ]
}
```

The following exception is occuring in the connect instance:

`2022-08-31 06:33:09,947 INFO Using SqlServer dialect TABLE "sample-stammdaten" absent (io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialect) [task-thread-sample-stammdaten-0]
java.lang.NullPointerException
        at io.confluent.connect.jdbc.dialect.SqlServerDatabaseDialect.getSqlType(SqlServerDatabaseDialect.java:198)
        at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.writeColumnSpec(GenericDatabaseDialect.java:1748)
        at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.lambda$writeColumnsSpec$34(GenericDatabaseDialect.java:1737)
        at io.confluent.connect.jdbc.util.ExpressionBuilder.append(ExpressionBuilder.java:558)
        at io.confluent.connect.jdbc.util.ExpressionBuilder$BasicListBuilder.of(ExpressionBuilder.java:597)
        at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.writeColumnsSpec(GenericDatabaseDialect.java:1739)
        at io.confluent.connect.jdbc.dialect.GenericDatabaseDialect.buildCreateTableStatement(GenericDatabaseDialect.java:1662)
        at io.confluent.connect.jdbc.sink.DbStructure.create(DbStructure.java:118)
        at io.confluent.connect.jdbc.sink.DbStructure.createOrAmendIfNecessary(DbStructure.java:67)
        at io.confluent.connect.jdbc.sink.BufferedRecords.add(BufferedRecords.java:148)
        at io.confluent.connect.jdbc.sink.JdbcDbWriter.lambda$write$9(JdbcDbWriter.java:124)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
        at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:74)
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:582)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:330)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-08-31 06:33:09,948 ERROR WorkerSinkTask{id=sample-stammdaten-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted. Error: null (org.apache.kafka.connect.runtime.WorkerSinkTask) [task-thread-sample-stammdaten-0]
org.apache.kafka.connect.errors.ConnectException
        at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:203)
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:582)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:330)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
2022-08-31 06:33:09,949 ERROR WorkerSinkTask{id=sample-stammdaten-0} Task threw an uncaught and unrecoverable exception. Task is being killed and will not recover until manually restarted (org.apache.kafka.connect.runtime.WorkerTask) [task-thread-sample-stammdaten-0]
org.apache.kafka.connect.errors.ConnectException: Exiting WorkerSinkTask due to unrecoverable exception.
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:610)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:330)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.iteration(WorkerSinkTask.java:232)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.execute(WorkerSinkTask.java:201)
        at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:188)
        at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:237)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.apache.kafka.connect.errors.ConnectException
        at io.confluent.connect.jdbc.sink.JdbcDbWriter.write(JdbcDbWriter.java:203)
        at io.confluent.connect.jdbc.sink.JdbcSinkTask.put(JdbcSinkTask.java:74)
        at org.apache.kafka.connect.runtime.WorkerSinkTask.deliverMessages(WorkerSinkTask.java:582)
        ... 10 more
2022-08-31 06:33:09,949 INFO Stopping task (io.confluent.connect.jdbc.sink.JdbcSinkTask) [task-thread-sample-stammdaten-0]`

When the table is created manually the connector is working as expected.

### Expected behavior
The connector is still able to determine the sql-type of decimal columns for creating and evolving tables

**Comment by gertschouten** [comment]
Hi there Noah,
Hope you are doing well.

I looked at the trace and have the following hypothesis:
1. You are getting a NPE at the following line of code:

https://github.com/Norsk-Tipping/kafka-connect-jdbc-flatten/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/SqlServerDatabaseDialect.java#L198

2. The field is defined as it is after field.schemaName() has been checked for NP in line 195. However, most likely the parameters of the schema are null, causing the get(Decimal.SCALE_FIELD) on schemaParameters() to be null.

3. The SCALE_FIELD parameter is set by the org.apache.kafka.connect.data.Decimal SchemaBuilder as we can see here:

https://github.com/apache/kafka/blob/a9ffabc4470b7847ec394e8e9f993326fd2c3390/connect/api/src/main/java/org/apache/kafka/connect/data/Decimal.java#L53

4. The Decimal SchemaBuilder is called by Confluent's Avro converter that converts from Avro to Connect:

https://github.com/confluentinc/schema-registry/blob/ce41679f50dc292022d871493c54a16e2ad4980b/avro-data/src/main/java/io/confluent/connect/avro/AvroData.java#L1740

---------
At this point we can conclude that the SqlServerDatabaseDialect is dependent on the parameters map of the Decimal field schema in order to correctly formulate its create table schema for schemas that include Decimal. Other dialects on the other hand don't depend on it, f.e. Netezza can simply say decimal without scale:

https://github.com/Norsk-Tipping/kafka-connect-jdbc-flatten/blob/master/src/main/java/io/confluent/connect/jdbc/dialect/NetezzaSqlDatabaseDialect.java#L200

Now the question is: What happened to the schema parameters of the field that are set during the conversion process, but no longer are there after the flatten transformation.

I believe this is a bug in the current codebase.
I believe the parameters of the Connect Schemas do currently not survive the transformation step.
However, I think it might be a quick fix.
----------

5. The Flatten transformation's core is to break down an incoming Connect Schema into subschemas on every place it encounters arrays. While breaking up the such Connect Schema into subschemas, it builds new subschema(s) by copying schema metadata from the original schema for relevant fields, utilizing org.apache.kafka.connect.data.SchemaBuilder.
While schema type and name are being copied over, it seems the parameter "copying" is missing there:

https://github.com/Norsk-Tipping/kafka-connect-jdbc-flatten/blob/master/src/main/java/no/norsktipping/kafka/connect/jdbc/sink/StreamFlatten/StreamFlatten/FlattenTransformation.java#L247

https://github.com/Norsk-Tipping/kafka-connect-jdbc-flatten/blob/master/src/main/java/no/norsktipping/kafka/connect/jdbc/sink/StreamFlatten/StreamFlatten/FlattenTransformation.java#L270

https://github.com/Norsk-Tipping/kafka-connect-jdbc-flatten/blob/master/src/main/java/no/norsktipping/kafka/connect/jdbc/sink/StreamFlatten/StreamFlatten/FlattenTransformation.java#L283

6. If you add .parameters to these three lines copying in the parameters from the source schema I believe the parameters will survive and those Dialects depending on it will be able to utilize them.

-------------
I myself am not the active maintainer of this connector any longer but I hope you are able to create a branch of this connector, apply the required changes to these three lines and can test if the hypothesis is correct and hopefully solves the NPE during create table towards SQLServer.
If tested with success a pull request can then be merged and others can benefit of that contribution.
